- name: Deploy edxapp
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
    CLUSTER_NAME: 'edxapp'
    USE_LETSENCRYPT: 'no'
  serial: "{{ serial_count }}"
  roles:
   - aws
   - role: automated
     AUTOMATED_USERS: "{{ EDXAPP_AUTOMATED_USERS | default({}) }}"
   - role: nginx
     nginx_sites:
     - lms
     - cms
     nginx_default_sites:
     - lms
     nginx_extra_sites: "{{ NGINX_EDXAPP_EXTRA_SITES }}"
     nginx_extra_configs: "{{ NGINX_EDXAPP_EXTRA_CONFIGS }}"
     nginx_redirects: "{{ NGINX_EDXAPP_CUSTOM_REDIRECTS }}"
   - configure-backups 
   - ec2-snapshot
   - { role: 'add-letsencrypt-certificate', when: USE_LETSENCRYPT == 'yes' and CMS_NGINX_SSL_CERTIFICATE is undefined and CMS_NGINX_SSL_KEY is undefined, nginx_default_sites: lms }
   - edxapp
   - { role: edxapp_async_assets,UPDATE_ASSETS_ASYNC: "{{ EDXAPP_UPDATE_ASSETS_ASYNC|default(false) }}"}
   - role: datadog
     when: COMMON_ENABLE_DATADOG
   - role: splunkforwarder
     when: COMMON_ENABLE_SPLUNKFORWARDER
   - role: newrelic
     when: COMMON_ENABLE_NEWRELIC
   - role: minos
     when: COMMON_ENABLE_MINOS
   - { role: edxapp_async_assets_check, CHECK_ASSETS_ASYNC: "{{ EDXAPP_CHECK_ASSETS_ASYNC|default(false) }}"}

